---

- include: docker_openssl_handler.yml
  vars:
    openssl_command: >
      openssl req -config openssl.cnf
      -key private/{{ ca_manager_key_name }} {{ key_decipher|default() }}
      -new -sha256
      -out csr/{{ ca_manager_request_file_name }}
      -subj '{{ ca_manager_subject_without_cn }}/CN={{ ca_manager_cn_name }}'
    command_name: "IntermediateCA - Create the intermediate certificate request"

- include: docker_openssl_handler.yml
  vars:
    openssl_command: >
      openssl ca -config {{ ca_manager_signin_ca_cert_location_docker }}/openssl.cnf -extensions v3_intermediate_ca
      -batch {{ signin_ca_key_decipher|default() }}
      -days 3650 -notext -md sha256
      -in csr/{{ ca_manager_request_file_name }}
      -out certs/{{ ca_manager_certificate_name }}
    command_name: "IntermediateCA - CA signs intermediate certificate from request"

- name: Create the certificate chain file
  shell: "cat {{ ca_manager_certificate_location }}/certs/{{ ca_manager_certificate_name }} {{ ca_manager_signin_ca_cert_fullchain_location }} > {{ ca_manager_certificate_location }}/certs/{{ ca_manager_fullchain_certificate_name }}"
