---

- include: docker_openssl_handler.yml
  vars:
    openssl_command: >
     req -config openssl.cnf
     -key private/{{ ca_manager_key_name }} {{ key_decipher|default() }}
     -new -x509 -days 7300 -sha256 -extensions v3_ca
     -out certs/{{ ca_manager_certificate_name }}
     -subj "{{ ca_manager_subject_without_cn }}/CN={{ ca_manager_cn_name }}"
    command_name: "RootCA - Create the root certificate"

- name: Create the root ca chain file
  shell: "cat {{ ca_manager_certificate_location }}/certs/{{ ca_manager_certificate_name }} > {{ ca_manager_certificate_location }}/certs/{{ ca_manager_fullchain_certificate_name }}"